# -*- coding: utf-8 -*-
"""AdvancedDISPLAY.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16y4BjLZ2whCJXJXn_zhK1x4dYii-X1y_
"""

import os
import librosa
from IPython.display import Audio,display
import librosa.display
import matplotlib.pyplot as plt

word_files={}
labels=[d for d in os.listdir(data_folder)
if os.path.isdir(os.path.join(data_folder,d)) and not d.startswith('.')]

for label in labels:
  label_path=os.path.join(data_folder,label)
  word_files[label]=[os.path.join(label_path,f) for f in os.listdir(label_path) if f.endswith('.wav')]


from IPython.core.pylabtools import figsize
from IPython.core.debugger import make_arrow
def linear_spec(waveform,sr):
  D=librosa.stft(waveform,n_fft=1024,hop_length=256) #convert time domain to frew doman
  '''
  parameters:
  n_ftt=fft window size, detemines fre resolution
  hop_length= step size b/w frames, determine time resolution
  ref.max: noralize valies so max is 0 db
  '''
  S_db=librosa.amplitude_to_db(np.abs(D), ref=np.max)

  librosa.display.specshow(S_db,sr=sr,hop_length=256,x_axis='time',y_axis='linear')

  plt.colorbar(label="Magnitude")
  plt.title("Linear spectrogram")
  plt.show()

def mel_spec(waveform,sr):
  D=librosa.feature.melspectrogram(y=waveform,sr=sr, n_mels=64, fmax=8000)
  S_mel_db=librosa.amplitude_to_db(np.abs(D),ref=np.max)

  plt.figure(figsize=(10,6))
  librosa.display.specshow(S_mel_db,x_axis='time', y_axis='mel', sr=sr, fmax=8000)
  plt.colorbar(label="db")
  plt.title("Log mel")
  plt.show()

def narrow_spec(wavrform,sr):
  D_narrow=librosa.stft(waveform,n_fft=2048,hop_length=512)
  S_narrow=librosa.amplitude_to_db(np.abs(D_narrow),ref=np.max)

  plt.figure(figsize=(10,6))
  librosa.display.specshow(S_narrow,sr=sr,hop_length=512,x_axis='time',y_axis='hz')
  plt.colorbar(label="dB")
  plt.title("Narrowband Spectrogram (Harmonics Visible)")
  plt.ylim(0,3000)
  plt.tight_layout()
  plt.show()

def wide_spec(waveform,sr):
  D_wide=librosa.stft(waveform,n_fft=512,hop_length=128)
  S_wide=librosa.amplitude_to_db(np.abs(D_wide),ref=np.max)

  plt.figure(figsize=(10,6))
  librosa.display.specshow(S_wide,sr=sr,hop_length=128,x_axis='time',y_axis='hz')
  plt.colorbar(label="dB")
  plt.title("Wideband Spectrogram (Formant Transitions)")
  plt.ylim(0,4000)
  plt.tight_layout()
  plt.show()

def mfcc_librosa(waveform,sr):
  mfcc_librosa=librosa.feature.mfcc(y=waveform, sr=sr, n_mfcc=13)
  print("Librosa MFCC shape:", mfcc_librosa.T.shape)
  plt.figure(figsize=(10,6))
  librosa.display.specshow(mfcc_librosa, sr=sr, x_axis='time')
  plt.title("MFCC (Librosa)")
  plt.colorbar()
  plt.show()


def mfcc_librosa_frame_7(waveform,sr):
  mfcc=librosa.feature.mfcc(y=waveform,sr=sr,n_mfcc=13)
  print("Librosa MFCC shape:",mfcc.T.shape)
  if mfcc.shape[1]<=7:
    print("Frame 7 not available. Total frames:",mfcc.shape[1])
    return None
  frame7=mfcc[:,7]
  print("MFCC values for frame 7:",frame7)

  plt.figure(figsize=(10,6))
  librosa.display.specshow(mfcc, sr=sr, x_axis='time')
  plt.axvline(x=librosa.frames_to_time(7,sr=sr),color='red',linestyle='--',label='Frame 7')
  plt.title("MFCC (Librosa) with Frame 7 highlighted")
  plt.colorbar()
  plt.legend()
  plt.show()

  return frame7



for label in labels:
  for file in word_files[label][:1]:
    waveform,sr=librosa.load(file,sr=16000)
    display(Audio(waveform,rate=sr))
    linear_spec(waveform,sr)
    mel_spec(waveform,sr)
    narrow_spec(waveform,sr)
    wide_spec(waveform,sr)
    mfcc_librosa(waveform,sr)
    mfcc_librosa_frame_7(waveform,sr)

