# -*- coding: utf-8 -*-
"""basicDISPLAY.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16y4BjLZ2whCJXJXn_zhK1x4dYii-X1y_
"""

import os
import librosa
from IPython.display import Audio,display
import librosa.display
import matplotlib.pyplot as plt

word_files={}
labels=[d for d in os.listdir(data_folder)
if os.path.isdir(os.path.join(data_folder,d)) and not d.startswith('.')]

for label in labels:
  label_path=os.path.join(data_folder,label)
  word_files[label]=[os.path.join(label_path,f) for f in os.listdir(label_path) if f.endswith('.wav')]


def show_waveform(waveform,sr=16000):
  plt.figure(figsize=(10,3))
  librosa.display.waveshow(waveform,sr=sr)
  plt.xlabel("Time")
  plt.ylabel("Amplitude")
  plt.title("Waveform")
  plt.show()

import numpy as np
for label in labels:
  for file in word_files[label][:2]:
    waveform,sr=librosa.load(file,sr=16000)
    print(f"File  loaded sucesssfully: {file}")
    print(f"File sampling rate: {sr}")
    print(f"Waveform shape: {waveform.shape}")
    print(f"Waveform datatype: {waveform.dtype}")
    duration=len(waveform)/sr
    print(f"Duration of audio: {duration}")
    display(Audio(waveform,rate=sr))

    if len(waveform)==2:
      print("Converting to mono:")
      waveform=np.meab(waveform,axis=0)
    else:
      print("File is in mono")

    print(f"Waveform of file: {file}")
    show_waveform(waveform,sr)

