# -*- coding: utf-8 -*-
"""CNN_SP.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16y4BjLZ2whCJXJXn_zhK1x4dYii-X1y_
"""

import requests
response=requests.get("https://raw.githubusercontent.com/Areeba128-ai/sp/main/pitch.ipynb")
print(response)

