# -*- coding: utf-8 -*-
"""LSTM_SP.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16y4BjLZ2whCJXJXn_zhK1x4dYii-X1y_
"""

!pip install tensorflow

import os
import librosa
import numpy as np
import matplotlib.pyplot as plt
import kagglehub
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM,Dense,Dropout
from tensorflow.keras.utils import to_categorical
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix,ConfusionMatrixDisplay,accuracy_score

path=kagglehub.dataset_download("clinton5575/mini-speech-commands")
data_folder=path

print("data_folder:",data_folder)
print("Top-level items:",os.listdir(data_folder)[:15])

def extract_features_lstm(file_path):
    signal,sr=librosa.load(file_path,sr=16000)
    mfcc=librosa.feature.mfcc(y=signal,sr=sr,n_mfcc=13)
    delta=librosa.feature.delta(mfcc)
    combined=np.vstack([mfcc,delta])
    combined=combined.T
    combined=(combined-np.mean(combined))/(np.std(combined)+1e-8)
    return combined

word_files={}
labels=[d for d in os.listdir(data_folder) if os.path.isdir(os.path.join(data_folder,d)) and not d.startswith('.')]

for label in labels:
    label_path=os.path.join(data_folder,label)
    word_files[label]=[os.path.join(label_path,f) for f in os.listdir(label_path) if f.endswith('.wav')]

print("labels:",labels)
print("example counts:",{lab:len(word_files[lab]) for lab in labels})

X=[]
y=[]

for label_idx,label in enumerate(labels):
    for file_path in word_files[label]:
        try:
            feats=extract_features_lstm(file_path)
            X.append(feats)
            y.append(label_idx)
        except:
            continue

X_padded=pad_sequences(X,padding='post',dtype='float32')
y_encoded=to_categorical(y,num_classes=len(labels))

X_train,X_test,y_train,y_test=train_test_split(
    X_padded,y_encoded,test_size=0.2,random_state=42,stratify=y
)

print("Input shape (samples,time,features):",X_train.shape)

model=Sequential([
    LSTM(64,return_sequences=True,input_shape=(X_train.shape[1],X_train.shape[2])),
    Dropout(0.3),
    LSTM(32),
    Dense(32,activation='relu'),
    Dropout(0.3),
    Dense(len(labels),activation='softmax')
])

model.compile(optimizer='adam',loss='categorical_crossentropy',metrics=['accuracy'])
model.summary()

history=model.fit(
    X_train,y_train,
    epochs=2,
    batch_size=16,
    validation_data=(X_test,y_test)
)

plt.plot(history.history['accuracy'],label='Train')
plt.plot(history.history['val_accuracy'],label='Val')
plt.title('LSTM Accuracy')
plt.legend()
plt.show()

def predict_command(file_path):
    feats=extract_features_lstm(file_path)
    feats_padded=pad_sequences([feats],maxlen=X_padded.shape[1],padding='post',dtype='float32')
    pred=model.predict(feats_padded,verbose=0)
    idx=int(np.argmax(pred))
    return labels[idx]

sample_test=word_files['no'][0]
print("Predicted:",predict_command(sample_test))

y_test_true=np.argmax(y_test,axis=1)
y_test_pred=np.argmax(model.predict(X_test),axis=1)

test_acc=accuracy_score(y_test_true,y_test_pred)
print("Test Accuracy:",test_acc)


cm=confusion_matrix(y_test_true,y_test_pred)

disp=ConfusionMatrixDisplay(
    confusion_matrix=cm,
    display_labels=labels
)

disp.plot(cmap="Blues",xticks_rotation=45)
plt.title("LSTM Confusion Matrix")
plt.show()

