# -*- coding: utf-8 -*-
"""rulebaseloop.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GAlVvHhaV9XV5ckVZC-dADvrJWzy3Di3
"""

import librosa
import numpy as np
import os
import kagglehub
import matplotlib.pyplot as plt

# 1. Load Dataset
path=kagglehub.dataset_download("clinton5575/mini-speech-commands")
data_folder=path

# 2. Select ONE group folder (example: "go")
group_folder=os.path.join(data_folder,"go")

# 3. Get first three audio files
audio_files=[f for f in os.listdir(group_folder) if f.endswith(".wav")][:3]

print("Analyzing Files:",audio_files)

# 4. Loop through first three files
for file in audio_files:
    audio_path=os.path.join(group_folder,file)
    signal,sr=librosa.load(audio_path,sr=None)

    # MFCC EXTRACTION
    mfcc=librosa.feature.mfcc(y=signal,sr=sr,n_mfcc=13)

    plt.figure(figsize=(6,3))
    plt.imshow(mfcc,aspect='auto')
    plt.title(f"MFCC:{file}")
    plt.colorbar()
    plt.show()

    # RULE 1: ENERGY
    energy=np.sum(signal**2)/len(signal)

    if energy>0.01:
        energy_label="Loud Sound Detected"
    else:
        energy_label="Silent Sound Detected"

    # RULE 2: ZCR
    zcr=np.mean(librosa.feature.zero_crossing_rate(signal))

    if zcr>0.1:
        zcr_label="Unvoiced Consonant"
    else:
        zcr_label="Voiced Sound"

    # FINAL RULE DECISION
    print("\nFILE:",file)
    print("Energy:",energy_label)
    print("ZCR:",zcr_label)

    if energy>0.01 and zcr>0.1:
        print("Rule Based Recognized Pattern:CONSONANT HEAVY WORD")
    else:
        print("Rule Based Recognized Pattern:VOWEL DOMINANT WORD")

