# -*- coding: utf-8 -*-
"""TemplateWithoutDTW.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GAlVvHhaV9XV5ckVZC-dADvrJWzy3Di3
"""

import librosa
import numpy as np
import os
import kagglehub
import matplotlib.pyplot as plt

# 1. Load Dataset
path=kagglehub.dataset_download("clinton5575/mini-speech-commands")
data_folder=path

# FEATURE EXTRACTION FUNCTION
def extract_mfcc(file):
    signal,sr=librosa.load(file)
    mfcc=librosa.feature.mfcc(y=signal,sr=sr,n_mfcc=13)
    return np.mean(mfcc,axis=1)

# LOAD TEMPLATES
template_folder="/kaggle/input/mini-speech-commands/go"
templates={}

for file in os.listdir(template_folder):
    if file.endswith(".wav"):
        word=file.replace(".wav","")
        path=os.path.join(template_folder,file)
        templates[word]=extract_mfcc(path)

print("Templates Loaded:",templates.keys())

# LOAD TEST SAMPLE
test_audio="/kaggle/input/mini-speech-commands/go/016e2c6d_nohash_0.wav"
test_features=extract_mfcc(test_audio)

# TEMPLATE MATCHING USING EUCLIDEAN DISTANCE
def euclidean_distance(x,y):
    return np.linalg.norm(x-y)

scores={}

for word in templates:
    dist=euclidean_distance(test_features,templates[word])
    scores[word]=dist

# RECOGNIZED WORD
recognized_word=min(scores,key=scores.get)

print("\nTEMPLATE MATCHING RESULT")
for key,value in scores.items():
    print(f"{key}→Distance:{value:.2f}")

print("\nRecognized Word:",recognized_word)

