# -*- coding: utf-8 -*-
"""TemplateWithDTW-Loop.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GAlVvHhaV9XV5ckVZC-dADvrJWzy3Di3
"""

import librosa
import numpy as np
import os
import kagglehub
import matplotlib.pyplot as plt

# Load Dataset
path=kagglehub.dataset_download("clinton5575/mini-speech-commands")
data_folder=path

# MFCC FEATURE EXTRACTION (FULL SEQUENCE)
def extract_mfcc(file):
    signal,sr=librosa.load(file,sr=None)
    mfcc=librosa.feature.mfcc(y=signal,sr=sr,n_mfcc=13)
    return mfcc.T

# DTW FUNCTION (FROM SCRATCH)
def dtw_distance(X,Y):
    n,m=len(X),len(Y)
    dtw=np.zeros((n,m))

    for i in range(n):
        for j in range(m):
            cost=np.linalg.norm(X[i]-Y[j])
            if i==0 and j==0:
                dtw[i,j]=cost
            elif i==0:
                dtw[i,j]=cost+dtw[i,j-1]
            elif j==0:
                dtw[i,j]=cost+dtw[i-1,j]
            else:
                dtw[i,j]=cost+min(dtw[i-1,j],dtw[i,j-1],dtw[i-1,j-1])

    return dtw[n-1,m-1]

# LOAD TEMPLATE SPEECH FILES
template_folder="/kaggle/input/mini-speech-commands/go"
templates={}

for file in os.listdir(template_folder):
    if file.endswith(".wav"):
        word=file.replace(".wav","")
        path=os.path.join(template_folder,file)
        templates[word]=extract_mfcc(path)

print("Templates Loaded:",templates.keys())

# FIRST THREE TEST FILES
test_files=[f for f in os.listdir(template_folder) if f.endswith(".wav")][:3]

# LOOP OVER FIRST THREE FILES
for test_file in test_files:
    test_path=os.path.join(template_folder,test_file)
    test_features=extract_mfcc(test_path)

    scores={}
    for word in templates:
        dist=dtw_distance(test_features,templates[word])
        scores[word]=dist

    recognized_word=min(scores,key=scores.get)

    print("\nFILE:",test_file)
    for key,value in scores.items():
        print(f"{key}→DTW Distance:{value:.2f}")
    print("FINAL RECOGNIZED WORD:",recognized_word)

